//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by camappgst.rc
//
#define ID_PANE_STATUS                  0
#define MENU_VDEVICE0                   10
#define MENU_VDEVICE1                   11
#define MENU_VDEVICE2                   12
#define MENU_VDEVICE3                   13
#define MENU_VDEVICE4                   14
#define MENU_VDEVICE5                   15
#define MENU_VDEVICE6                   16
#define MENU_VDEVICE7                   17
#define MENU_VDEVICE8                   18
#define MENU_VDEVICE9                   19
#define IDD_ABOUTBOX                    100
#define IDD_PROPPAGE_CAMERA_CONTROLS    107
#define IDR_MAINFRAME                   128
#define IDR_CAMAPP_GST_TYPE             130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDD_DEVICE_CAPS                 310
#define IDD_PRINT_ANALYSIS_OPTS         312
#define IDD_PROPPAGE_VIDEO_PROC         313
#define IDC_FORMAT                      1001
#define IDC_STATIC_FORMAT               1002
#define IDC_COMBO_FRAME_SIZE            1003
#define IDC_STATIC_FRAME_SIZE           1004
#define IDC_COMBO_FRAMERATE             1005
#define IDC_STATIC_FRAMERATE            1006
#define IDC_GROUP_GRAYSCALE             1008
#define IDC_RADIO_GRAY_WHOLE            1009
#define IDC_RADIO_GRAY_AOI              1010
#define IDC_RADIO_GRAY_NONE             1011
#define IDC_GROUP_BLACKOUT              1012
#define IDC_RADIO_BLACK_WHOLE           1013
#define IDC_RADIO_BLACK_AOI             1014
#define IDC_RADIO_BLACK_NONE            1015
#define IDC_GROUP_AOI                   1016
#define IDC_EDIT_AOI_HEIGHT             1017
#define IDC_EDIT_AOI_PARTITIONS         1018
#define IDC_STATIC_AOI_HEIGHT           1019
#define IDC_STATIC_AOI_PARTITIONS       1020
#define IDC_CHECK_CONNECT_VALUES        1021
#define IDC_BUTTON1                     1022
#define IDC_BUTTON_APPLY                1022
#define IDC_BUTTON_DEFAULT              1022
#define IDC_BUTTON_VID_PROC_AMP_DEFAULT 1022
#define IDC_STATIC_AUTO                 1028
#define IDC_COMBO_PL_FREQ               1053
#define IDC_SLIDER_ZOOM                 1054
#define IDC_EDIT_ZOOM                   1055
#define IDC_CHECK_ZOOM                  1056
#define IDC_STATIC_ZOOM                 1057
#define IDC_STATIC_FOCUS                1058
#define IDC_SLIDER_FOCUS                1059
#define IDC_EDIT_FOCUS                  1060
#define IDC_CHECK_FOCUS                 1061
#define IDC_STATIC_EXPOSURE             1062
#define IDC_SLIDER_EXPOSURE             1063
#define IDC_EDIT_EXPOSURE               1064
#define IDC_CHECK_EXPOSURE              1065
#define IDC_STATIC_APERTURE             1066
#define IDC_SLIDER_APERTURE             1067
#define IDC_EDIT_APERTURE               1068
#define IDC_CHECK_APERTURE              1069
#define IDC_STATIC_PAN                  1070
#define IDC_SLIDER_PAN                  1071
#define IDC_EDIT_PAN                    1072
#define IDC_CHECK_PAN                   1073
#define IDC_STATIC_TILT                 1074
#define IDC_SLIDER_TILT                 1075
#define IDC_EDIT_TILT                   1076
#define IDC_CHECK_TILT                  1077
#define IDC_STATIC_ROLL                 1078
#define IDC_SLIDER_ROLL                 1079
#define IDC_EDIT_ROLL                   1080
#define IDC_CHECK_ROLL                  1081
#define IDC_CHECK_LLC                   1082
#define IDC_BUTTON_CAM_CTRL_DEFAULT     1083
#define IDC_STATIC_BRIGHTNESS           1084
#define IDC_STATIC_CONTRAST             1085
#define IDC_STATIC_HUE                  1086
#define IDC_STATIC_SATURATION           1087
#define IDC_STATIC_SHARPNESS            1088
#define IDC_STATIC_GAMMA                1089
#define IDC_STATIC_WHITE_BAL            1090
#define IDC_STATIC_BACKLIGHT_COMP       1091
#define IDC_STATIC_GAIN                 1092
#define IDC_STATIC_PL_FREQ              1093
#define IDC_LIST1                       1094
#define IDC_GROUP_ANALYSIS_TYPE         2001
#define IDC_RADIO_INTENSITY             2002
#define IDC_RADIO_MEAN                  2003
#define IDC_RADIO_HISTOGRAM             2004
#define IDC_RADIO_ANALYSIS_NONE         2005
#define IDC_CHECK_BRIGHTNESS            2010
#define IDC_CHECK_CONTRAST              2011
#define IDC_CHECK_HUE                   2012
#define IDC_CHECK_SATURATION            2013
#define IDC_CHECK_SHARPNESS             2014
#define IDC_CHECK_GAMMA                 2015
#define IDC_CHECK_WHITE_BAL             2016
#define IDC_CHECK_BACKLIGHT_COMP        2017
#define IDC_CHECK_GAIN                  2018
#define IDC_CHECK_COLOR_ENB             2019
#define IDC_SLIDER_BRIGHTNESS           3010
#define IDC_SLIDER_CONTRAST             3011
#define IDC_SLIDER_HUE                  3012
#define IDC_SLIDER_SATURATION           3013
#define IDC_SLIDER_SHARPNESS            3014
#define IDC_SLIDER_GAMMA                3015
#define IDC_SLIDER_WHITE_BAL            3016
#define IDC_SLIDER_BACKLIGHT_COMP       3017
#define IDC_SLIDER_GAIN                 3018
#define IDC_EDIT_BRIGHTNESS             4010
#define IDC_EDIT_CONTRAST               4011
#define IDC_EDIT_HUE                    4012
#define IDC_EDIT_SATURATION             4013
#define IDC_EDIT_SHARPNESS              4014
#define IDC_EDIT_GAMMA                  4015
#define IDC_EDIT_WHITE_BAL              4016
#define IDC_EDIT_BACKLIGHT_COMP         4017
#define IDC_EDIT_GAIN                   4018
#define ID_OPTIONS_PREVIEW              32771
#define ID_SOURCE_KERNELSTREAMING       32772
#define ID_SOURCE_MEDIAFOUNDATION       32773
#define ID_SOURCE_DIRECTSHOW            32774
#define ID_OPTIONS_CAMERAPROPERTIES     32775
#define ID_OPTIONS_SHOWFPS              32776
#define ID_SINK_AUTO                    32777
#define ID_SINK_DIRECT3D11              32778
#define ID_SINK_DIRECT3D9               32779
#define ID_SINK_OPENGL                  32780
#define ID_MENU_PRINT_ANALYSIS_OPTS     32781
#define ID_OPTIONS_CAMERASETTINGS       32783
#define ID_DEVICE_START                 33000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        315
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
