//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by camappgst.rc
//
#define ID_PANE_STATUS                  0
#define MENU_VDEVICE0                   10
#define MENU_VDEVICE1                   11
#define MENU_VDEVICE2                   12
#define MENU_VDEVICE3                   13
#define MENU_VDEVICE4                   14
#define MENU_VDEVICE5                   15
#define MENU_VDEVICE6                   16
#define MENU_VDEVICE7                   17
#define MENU_VDEVICE8                   18
#define MENU_VDEVICE9                   19
#define IDD_ABOUTBOX                    100
#define IDD_PROPPAGE_CAMERA_CONTROLS    107
#define IDR_MAINFRAME                   128
#define IDR_CAMAPP_GST_TYPE             130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDD_DEVICE_CAPS                 310
#define IDD_PRINT_ANALYSIS_OPTS         312
#define IDD_PROPPAGE_VIDEO_PROC         313
#define IDB_PNG_PREVIEW                 319
#define IDB_BITMAP1                     321
#define IDB_PNG_CAMERA_SETTINGS         328
#define IDB_PNG_VIDEO_SETTINGS          329
#define IDB_PNG_PRINT_ANALYSIS          330
#define IDB_PNG_PREVIEW_STOP            331
#define IDB_PNG_SNAPSHOT                332
#define IDB_PNG_FPS                     336
#define IDB_PNG_FPS_OFF                 337
#define IDB_PNG_BARCODE_READER          338
#define IDB_PNG_BARCODE                 339
#define IDB_PNG_BARCODE_OFF             340
#define IDB_PNG_LOCATION                341
#define IDD_DIALOG_BARCODE_TYPES        342
#define IDB_PNG_LOCATION_OFF            344
#define IDB_PNG_BARCODE_FORMATS         345
#define IDR_BARCODE_OUTPUT_POPUP        346
#define IDB_PNG_OCR                     347
#define IDD_DIALOG_REG_SETTINGS         348
#define IDB_PNG_ZOOM_IN                 349
#define IDB_PNG1                        350
#define IDB_PNG_ZOOM_OUT                350
#define IDB_PNG_PAN_LEFT                352
#define IDB_PNG_PAN_RIGHT               353
#define IDB_PNG_TILT_UP                 354
#define IDB_PNG_TILT_DOWN               355
#define IDC_FORMAT                      1001
#define IDC_STATIC_FORMAT               1002
#define IDC_COMBO_FRAME_SIZE            1003
#define IDC_STATIC_FRAME_SIZE           1004
#define IDC_COMBO_FRAMERATE             1005
#define IDC_STATIC_FRAMERATE            1006
#define IDC_GROUP_GRAYSCALE             1008
#define IDC_RADIO_GRAY_WHOLE            1009
#define IDC_RADIO_GRAY_AOI              1010
#define IDC_RADIO_GRAY_NONE             1011
#define IDC_GROUP_BLACKOUT              1012
#define IDC_RADIO_BLACK_WHOLE           1013
#define IDC_RADIO_BLACK_AOI             1014
#define IDC_RADIO_BLACK_NONE            1015
#define IDC_GROUP_AOI                   1016
#define IDC_EDIT_AOI_HEIGHT             1017
#define IDC_EDIT_AOI_PARTITIONS         1018
#define IDC_STATIC_AOI_HEIGHT           1019
#define IDC_STATIC_AOI_PARTITIONS       1020
#define IDC_CHECK_CONNECT_VALUES        1021
#define IDC_BUTTON_APPLY                1022
#define IDC_BUTTON_DEFAULT              1022
#define IDC_BUTTON_VID_PROC_AMP_DEFAULT 1022
#define IDC_STATIC_AUTO                 1028
#define IDC_COMBO_PL_FREQ               1053
#define IDC_STATIC_ZOOM                 1057
#define IDC_STATIC_FOCUS                1058
#define IDC_STATIC_EXPOSURE             1062
#define IDC_STATIC_APERTURE             1066
#define IDC_STATIC_PAN                  1070
#define IDC_STATIC_TILT                 1074
#define IDC_STATIC_ROLL                 1078
#define IDC_CHECK_LLC                   1082
#define IDC_BUTTON_CAM_CTRL_DEFAULT     1083
#define IDC_STATIC_BRIGHTNESS           1084
#define IDC_STATIC_CONTRAST             1085
#define IDC_STATIC_HUE                  1086
#define IDC_STATIC_SATURATION           1087
#define IDC_STATIC_SHARPNESS            1088
#define IDC_STATIC_GAMMA                1089
#define IDC_STATIC_WHITE_BAL            1090
#define IDC_STATIC_BACKLIGHT_COMP       1091
#define IDC_STATIC_GAIN                 1092
#define IDC_STATIC_PL_FREQ              1093
#define IDC_CHECK_BARCODE_ALL           1095
#define IDC_CHECK_BARCODE_LINEAR        1096
#define IDC_CHECK_BARCODE_MATRIX        1097
#define IDC_CHECK_BARCODE_CODABAR       1098
#define IDC_CHECK_BARCODE_CODE39        1099
#define IDC_CHECK_BARCODE_CODE93        1100
#define IDC_CHECK_BARCODE_CODE128       1101
#define IDC_CHECK_BARCODE_EAN8          1102
#define IDC_CHECK_BARCODE_EAN13         1103
#define IDC_CHECK_BARCODE_ITF           1104
#define IDC_CHECK_BARCODE_DATABAR       1105
#define IDC_CHECK_BARCODE_DATABAR_EXPANDED 1106
#define IDC_CHECK_BARCODE_DATABAR_LIMITED 1107
#define IDC_CHECK_BARCODE_DX_FILM_EDGE  1108
#define IDC_CHECK_BARCODE_UPCA          1109
#define IDC_CHECK_BARCODE_UPCE          1110
#define IDC_CHECK_BARCODE_AZTEC         1111
#define IDC_CHECK_BARCODE_DATA_MATRIX   1112
#define IDC_CHECK_BARCODE_MAXI_CODE     1113
#define IDC_CHECK_BARCODE_PDF417        1114
#define IDC_CHECK_BARCODE_QR_CODE       1115
#define IDC_CHECK_BARCODE_MICRO_QR_CODE 1116
#define IDC_CHECK_BARCODE_RM_QR_CODE    1117
#define IDC_STATIC_LINEAR_CODES         1118
#define IDC_STATIC_MATRIX_CODES         1119
#define IDC_STATIC_ALL_CODES            1120
#define IDC_STATIC_REG_SETTINGS         1121
#define IDC_STATIC_REG_PARENT_KEY       1122
#define IDC_COMBO_REG_AOI_PARENT_KEY    1123
#define IDC_STATIC_REG_SUB_KEY          1124
#define IDC_EDIT_REG_SUB_KEY            1125
#define IDC_STATIC_AOI_FLAG             1126
#define IDC_EDIT_REG_AOI_FLAG           1127
#define IDC_STATIC_REG_SNAPSHOT_FLAG    1128
#define IDC_EDIT_REG_SNAPSHOT_FLAG      1129
#define IDC_EDIT_REG_SNAPSHOT_DIR       1130
#define IDC_STATIC_BARCODE_FLAG         1131
#define IDC_GROUP_REG_GENERAL           1132
#define IDC_GROUP_REG_PRINT_ANALYSIS    1133
#define IDC_GROUP_REG_SNAPSHOT          1134
#define IDC_EDIT_REG_BARCODE_FLAG       1135
#define IDC_GROUP_REG_BARCODE           1136
#define IDC_GROUP_REG_PREVIEW           1137
#define IDC_STATIC_REG_START_STOP_FLAG  1138
#define IDC_EDIT_REG_START_STOP_FLAG    1139
#define IDC_GROUP_BARCODE_AOI           1140
#define IDC_STATIC_COLUMN_START_X       1141
#define IDC_EDIT_COLUMN_START_X         1142
#define IDC_STATIC_COLUMN_WIDTH         1143
#define IDC_EDIT_COLUMN_WIDTH           1144
#define IDC_GROUP_ANALYSIS_TYPE         2001
#define IDC_RADIO_INTENSITY             2002
#define IDC_RADIO_MEAN                  2003
#define IDC_RADIO_HISTOGRAM             2004
#define IDC_RADIO_ANALYSIS_TOTAL        2005
#define IDC_RADIO_ANALYSIS_NONE         2006
#define IDC_CHECK_BRIGHTNESS            2010
#define IDC_CHECK_CONTRAST              2011
#define IDC_CHECK_HUE                   2012
#define IDC_CHECK_SATURATION            2013
#define IDC_CHECK_SHARPNESS             2014
#define IDC_CHECK_GAMMA                 2015
#define IDC_CHECK_WHITE_BAL             2016
#define IDC_CHECK_BACKLIGHT_COMP        2017
#define IDC_CHECK_GAIN                  2018
#define IDC_CHECK_COLOR_ENB             2019
#define IDC_CHECK_ZOOM                  2020
#define IDC_CHECK_FOCUS                 2021
#define IDC_CHECK_EXPOSURE              2022
#define IDC_CHECK_APERTURE              2023
#define IDC_CHECK_PAN                   2024
#define IDC_CHECK_TILT                  2025
#define IDC_CHECK_ROLL                  2026
#define IDC_SLIDER_BRIGHTNESS           3010
#define IDC_SLIDER_CONTRAST             3011
#define IDC_SLIDER_HUE                  3012
#define IDC_SLIDER_SATURATION           3013
#define IDC_SLIDER_SHARPNESS            3014
#define IDC_SLIDER_GAMMA                3015
#define IDC_SLIDER_WHITE_BAL            3016
#define IDC_SLIDER_BACKLIGHT_COMP       3017
#define IDC_SLIDER_GAIN                 3018
#define IDC_SLIDER_ZOOM                 3020
#define IDC_SLIDER_FOCUS                3021
#define IDC_SLIDER_EXPOSURE             3022
#define IDC_SLIDER_APERTURE             3023
#define IDC_SLIDER_PAN                  3024
#define IDC_SLIDER_TILT                 3025
#define IDC_SLIDER_ROLL                 3026
#define IDC_EDIT_BRIGHTNESS             4010
#define IDC_EDIT_CONTRAST               4011
#define IDC_EDIT_HUE                    4012
#define IDC_EDIT_SATURATION             4013
#define IDC_EDIT_SHARPNESS              4014
#define IDC_EDIT_GAMMA                  4015
#define IDC_EDIT_WHITE_BAL              4016
#define IDC_EDIT_BACKLIGHT_COMP         4017
#define IDC_EDIT_GAIN                   4018
#define IDC_EDIT_ZOOM                   4020
#define IDC_EDIT_FOCUS                  4021
#define IDC_EDIT_EXPOSURE               4022
#define IDC_EDIT_APERTURE               4023
#define IDC_EDIT_PAN                    4024
#define IDC_EDIT_TILT                   4025
#define IDC_EDIT_ROLL                   4026
#define IDC_LIST_BARCODE                4027
#define ID_OPTIONS_PREVIEW              32771
#define ID_SOURCE_KERNELSTREAMING       32772
#define ID_SOURCE_MEDIAFOUNDATION       32773
#define ID_SOURCE_DIRECTSHOW            32774
#define ID_OPTIONS_CAMERAPROPERTIES     32775
#define ID_OPTIONS_SHOWFPS              32776
#define ID_SINK_AUTO                    32777
#define ID_SINK_DIRECT3D11              32778
#define ID_SINK_DIRECT3D9               32779
#define ID_SINK_OPENGL                  32780
#define ID_MENU_PRINT_ANALYSIS_OPTS     32781
#define ID_OPTIONS_CAMERASETTINGS       32783
#define ID_Menu                         32786
#define ID_OPTIONS_SNAPSHOT             32787
#define ID_BARCODE_SCAN                 32788
#define ID_BARCODE_SHOWLOCATION         32789
#define ID_BARCODE_SHOW_LOCATION        32790
#define ID_BARCODE_TYPESTOSCAN          32791
#define ID_BARCODE_TYPES                32792
#define ID_POPUP_CLEAR                  32793
#define ID_POPUP_COPY                   32794
#define ID_POPUP_DELETE                 32795
#define ID_OCR_RUN_OCR                  32799
#define ID_OPTIONS_REGISTRYSETTINGS     32800
#define ID_OPTIONS_AUTOSTART            32801
#define ID_OPTIONS_SNAPSHOT_AS_BMP      32802
#define ID_OPTIONS_COMPARE_SNAPSHOT     32803
#define ID_OPTIONS_ZOOMIN               32804
#define ID_OPTIONS_ZOOMOUT              32805
#define ID_OPTIONS_PAN_LEFT             32806
#define ID_OPTIONS_PAN_RIGHT            32807
#define ID_OPTIONS_TILT_UP              32808
#define ID_OPTIONS_TILT_DOWN            32809
#define ID_DEVICE_START                 33000
#define ID_VIEW_BARCODEWND              33001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        356
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1145
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
